@startuml
!include .\\.\Program.puml
!include .\\.\Config\IConfigurable.puml
!include .\\.\Core\Utility.puml
!include .\\.\Visualization\IFrequencyReactive.puml
!include .\\.\Visualization\ISpikeReactive.puml
!include .\\.\Visualization\IVisualization.puml
!include .\\.\Visualization\IVolumeReactive.puml
!include .\\.\Visualization\VisualizationMode.puml
!include .\\.\Visualization\VisualizationOrigin.puml
!include .\\.\Config\Font\Font.puml
!include .\\.\Config\Font\FontFace.puml
!include .\\.\Config\Font\RasterFontType.puml
!include .\\.\Config\Settings\AudioCaptureSettings.puml
!include .\\.\Config\Settings\ConsoleSettings.puml
!include .\\.\Config\Settings\EqualizerSettings.puml
!include .\\.\Config\Settings\FftSettings.puml
!include .\\.\Config\Settings\FontSettings.puml
!include .\\.\Config\Settings\GlobalSettings.puml
!include .\\.\Config\Settings\RendererSettings.puml
!include .\\.\Config\Settings\RingsSettings.puml
!include .\\.\Config\Settings\Settings.puml
!include .\\.\Config\Settings\SettingsManager.puml
!include .\\.\Config\Settings\ShapeSettings.puml
!include .\\.\Config\Settings\WaterfallSettings.puml
!include .\\.\Core\Audio\AudioCapture.puml
!include .\\.\Core\Audio\FftAnalyzer.puml
!include .\\.\Core\CLI\CLI.puml
!include .\\.\Core\Rendering\ConsoleWindow.puml
!include .\\.\Core\Rendering\RenderMode.puml
!include .\\.\Core\Rendering\ScreenBuffer.puml
!include .\\.\Visualization\Equalizer\EqColorMode.puml
!include .\\.\Visualization\Equalizer\EqDirection.puml
!include .\\.\Visualization\Equalizer\Equalizer.puml
!include .\\.\Visualization\Rings\Ring.puml
!include .\\.\Visualization\Rings\RingColorMode.puml
!include .\\.\Visualization\Rings\Rings.puml
!include .\\.\Visualization\Shape\Shape.puml
!include .\\.\Visualization\Shape\ShapeLayout.puml
!include .\\.\Visualization\Shape\ShapeType.puml
!include .\\.\Visualization\Waterfall\Waterfall.puml
!include .\\.\Visualization\Waterfall\WaterfallMode.puml
!include .\\.\Visualization\Waterfall\WaterfallStream.puml
!include .\\.\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\.\obj\Debug\net8.0\TERMINAL_FREQUENCY.AssemblyInfo.puml
!include .\\.\obj\Debug\net8.0\TERMINAL_FREQUENCY.GlobalUsings.g.puml
!include .\\.\obj\Debug\net8.0\win-x64\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\.\obj\Debug\net8.0\win-x64\TERMINAL_FREQUENCY.AssemblyInfo.puml
!include .\\.\obj\Debug\net8.0\win-x64\TERMINAL_FREQUENCY.GlobalUsings.g.puml
!include .\\.\obj\Release\net8.0\win-x64\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\.\obj\Release\net8.0\win-x64\TERMINAL_FREQUENCY.AssemblyInfo.puml
!include .\\.\obj\Release\net8.0\win-x64\TERMINAL_FREQUENCY.GlobalUsings.g.puml
@enduml
